// Music.c
// Store music file representations and note processing
// Lab 5
// Samuel Zhang and Joel Wang
// 2/19/18

#include "Music.h"
#include "Main.h"
#include "../inc/tm4c123gh6pm.h"


#define PF1 (*((volatile uint32_t *)0x40025008))

Note BeautyAndTheBeastL[] = {
{ 0 , Quarter , Trumpet } ,
{ B3 , Quarter , Trumpet } ,
{ C4 , Quarter , Trumpet } ,
{ D4 , Quarter , Trumpet } ,
{ E4 , Quarter , Trumpet } ,
{ D4 , Eighth , Trumpet } ,
{ C4 , Eighth , Trumpet } ,
{ D4 ,Half , Trumpet } ,
{ 0 , Quarter , Trumpet } ,
{ B3 , Quarter , Trumpet } ,
{ C4 , Quarter , Trumpet } ,
{ D4 , Quarter , Trumpet } ,
{ E4 , Quarter , Trumpet } ,
{ D4 , Eighth , Trumpet } ,
{ C4 , Eighth , Trumpet } ,
{ D4 , Quarter , Trumpet } ,
{ C4 , Quarter , Trumpet } ,
{ B3 , Half , Trumpet } ,
{ B3 , Eighth , Trumpet } ,
{ D4 , Eighth , Trumpet } ,
{ F4S , Eighth , Trumpet } ,
{ G4, Eighth , Trumpet } ,
{ C4 , Quarter , Trumpet } ,
{ C4 , Half , Trumpet } ,
{ 0 , Quarter , Trumpet } ,
{0, Whole, Flute}
};

Note BeautyAndTheBeastR[] = {			
{ G3 , Half , Trumpet } ,
{ E3 , Quarter , Trumpet } ,
{ F3S , Quarter , Trumpet } ,
{ G3 , Half , Trumpet } ,
{ F3S , Quarter , Trumpet } ,
{ D3 , Quarter , Trumpet } ,
{ G3 , Half , Trumpet } ,
{ E3 ,Quarter , Trumpet } ,
{ F3S , Quarter , Trumpet } ,
{ G3 , Half , Trumpet } ,
{ F3S , Half , Trumpet } ,
{ G3 , Quarter , Trumpet } ,
{ G3 , Quarter , Trumpet } ,
{ G3 , Half , Trumpet } ,
{ A3 , Eighth , Trumpet } ,
{ A3 , Quarter , Trumpet } ,
{ E3 , Eighth , Trumpet } ,
{ G3 , Quarter , Trumpet } ,
{ F3 , Quarter , Trumpet } ,
{ G3 , Quarter , Trumpet } ,
{ G3 , Half , Trumpet } ,
{ D3, Quarter , Trumpet } ,
{ C3 , Quarter , Trumpet } ,
{ C3 , Eighth , Trumpet } ,
{ E3 , Eighth , Trumpet } ,
{ G3 , Quarter , Trumpet } ,
{ F3S , Quarter , Trumpet } ,
{0, Whole, Flute}
};

Note mary_lamb[] = {
	{ 0 , Quarter , Trumpet },
	{B, Quarter, Flute},
	{A, Quarter, Flute},
	{G, Quarter, Flute},
	{A, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Half, Flute},
	{A, Quarter, Flute},
	{A, Quarter, Flute},
	{A, Half, Flute},
	{B, Quarter, Flute},
	{D, Quarter, Flute},
	{D, Half, Flute},
	{B, Quarter, Flute},
	{A, Quarter, Flute},
	{G, Quarter, Flute},
	{A, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Quarter, Flute},
	{A, Quarter, Flute},
	{A, Quarter, Flute},
	{B, Quarter, Flute},
	{A, Quarter, Flute},
	{G, Whole, Flute},
	{B, Quarter, Flute},
	{A, Quarter, Flute},
	{G, Quarter, Flute},
	{A, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Half, Flute},
	{A, Quarter, Flute},
	{A, Quarter, Flute},
	{A, Half, Flute},
	{B, Quarter, Flute},
	{D, Quarter, Flute},
	{D, Half, Flute},
	{B, Quarter, Flute},
	{A, Quarter, Flute},
	{G, Quarter, Flute},
	{A, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Quarter, Flute},
	{A, Quarter, Flute},
	{A, Quarter, Flute},
	{B, Quarter, Flute},
	{A, Quarter, Flute},
	{G, Quarter, Flute},
	{D, Quarter, Flute},
	{B, Quarter, Flute},
	{A, Quarter, Flute},
	{G, Quarter, Flute},
	{A, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Half, Flute},
	{A, Quarter, Flute},
	{A, Quarter, Flute},
	{A, Half, Flute},
	{B, Quarter, Flute},
	{D, Quarter, Flute},
	{D, Half, Flute},
	{B, Quarter, Flute},
	{A, Quarter, Flute},
	{G, Quarter, Flute},
	{A, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Quarter, Flute},
	{A, Quarter, Flute},
	{A, Quarter, Flute},
	{B, Quarter, Flute},
	{A, Quarter, Flute},
	{G, Quarter, Flute},
	{D, Quarter, Flute},
	{B, Quarter, Flute},
	{A, Quarter, Flute},
	{G, Quarter, Flute},
	{A, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Half, Flute},
	{A, Quarter, Flute},
	{A, Quarter, Flute},
	{A, Half, Flute},
	{B, Quarter, Flute},
	{D, Quarter, Flute},
	{D, Half, Flute},
	{B, Quarter, Flute},
	{A, Quarter, Flute},
	{G, Quarter, Flute},
	{A, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Quarter, Flute},
	{B, Quarter, Flute},
	{A, Quarter, Flute},
	{A, Quarter, Flute},
	{B, Quarter, Flute},
	{A, Quarter, Flute},
	{G, Whole, Flute},
	{0, Whole, Flute}
};

Note ff7_pre[] = {				// Final Fantasy 7 Prelude, 128 notes total
{ B3 , Eighth , Trumpet } ,
{ C3 , Eighth , Trumpet } ,
{ D3 , Eighth , Trumpet } ,
{ F3 , Eighth , Trumpet } ,
{ B3 , Eighth , Trumpet } ,
{ C4 , Eighth , Trumpet } ,
{ D4 , Eighth , Trumpet } ,
{ F4 , Eighth , Trumpet } ,
{ B4 , Eighth , Trumpet } ,
{ C5 , Eighth , Trumpet } ,
{ D5 , Eighth , Trumpet } ,
{ F5 , Eighth , Trumpet } ,
{ B5 , Eighth , Trumpet } ,
{ C6 , Eighth , Trumpet } ,
{ D6 , Eighth , Trumpet } ,
{ E6 , Eighth , Trumpet } ,
{ A6 , Eighth , Trumpet } ,
{ E6 , Eighth , Trumpet } ,
{ D6 , Eighth , Trumpet } ,
{ C6 , Eighth , Trumpet } ,
{ B5 , Eighth , Trumpet } ,
{ F5 , Eighth , Trumpet } ,
{ D5 , Eighth , Trumpet } ,
{ C5 , Eighth , Trumpet } ,
{ B4 , Eighth , Trumpet } ,
{ F4 , Eighth , Trumpet } ,
{ D4 , Eighth , Trumpet } ,
{ C4 , Eighth , Trumpet } ,
{ B3 , Eighth , Trumpet } ,
{ F3 , Eighth , Trumpet } ,
{ D3 , Eighth , Trumpet } ,
{ C3 , Eighth , Trumpet } ,
{ G3 , Eighth , Trumpet } ,
{ A3 , Eighth , Trumpet } ,
{ B3 , Eighth , Trumpet } ,
{ D3 , Eighth , Trumpet } ,
{ G3 , Eighth , Trumpet } ,
{ A3 , Eighth , Trumpet } ,
{ B3 , Eighth , Trumpet } ,
{ D4 , Eighth , Trumpet } ,
{ G4 , Eighth , Trumpet } ,
{ A4 , Eighth , Trumpet } ,
{ B4 , Eighth , Trumpet } ,
{ D5 , Eighth , Trumpet } ,
{ G5 , Eighth , Trumpet } ,
{ A5 , Eighth , Trumpet } ,
{ B5 , Eighth , Trumpet } ,
{ D6 , Eighth , Trumpet } ,
{ E6 , Eighth , Trumpet } ,
{ A6 , Eighth , Trumpet } ,
{ E6 , Eighth , Trumpet } ,
{ D6 , Eighth , Trumpet } ,
{ C6 , Eighth , Trumpet } ,
{ B5 , Eighth , Trumpet } ,
{ F5 , Eighth , Trumpet } ,
{ D5 , Eighth , Trumpet } ,
{ C5 , Eighth , Trumpet } ,
{ B4 , Eighth , Trumpet } ,
{ F4 , Eighth , Trumpet } ,
{ D4 , Eighth , Trumpet } ,
{ C4 , Eighth , Trumpet } ,
{ B3 , Eighth , Trumpet } ,
{ F3 , Eighth , Trumpet } ,
{ D3 , Eighth , Trumpet } ,
{ B3 , Eighth , Trumpet } ,
{ C3 , Eighth , Trumpet } ,
{ D3 , Eighth , Trumpet } ,
{ F3 , Eighth , Trumpet } ,
{ B3 , Eighth , Trumpet } ,
{ C4 , Eighth , Trumpet } ,
{ D4 , Eighth , Trumpet } ,
{ F4 , Eighth , Trumpet } ,
{ B4 , Eighth , Trumpet } ,
{ C5 , Eighth , Trumpet } ,
{ D5 , Eighth , Trumpet } ,
{ F5 , Eighth , Trumpet } ,
{ B5 , Eighth , Trumpet } ,
{ C6 , Eighth , Trumpet } ,
{ D6 , Eighth , Trumpet } ,
{ E6 , Eighth , Trumpet } ,
{ A6 , Eighth , Trumpet } ,
{ E6 , Eighth , Trumpet } ,
{ D6 , Eighth , Trumpet } ,
{ C6 , Eighth , Trumpet } ,
{ B5 , Eighth , Trumpet } ,
{ F5 , Eighth , Trumpet } ,
{ D5 , Eighth , Trumpet } ,
{ C5 , Eighth , Trumpet } ,
{ B4 , Eighth , Trumpet } ,
{ F4 , Eighth , Trumpet } ,
{ D4 , Eighth , Trumpet } ,
{ C4 , Eighth , Trumpet } ,
{ B3 , Eighth , Trumpet } ,
{ F3 , Eighth , Trumpet } ,
{ D3 , Eighth , Trumpet } ,
{ C3 , Eighth , Trumpet } ,
{ G3 , Eighth , Trumpet } ,
{ A3 , Eighth , Trumpet } ,
{ B3 , Eighth , Trumpet } ,
{ D3 , Eighth , Trumpet } ,
{ G3 , Eighth , Trumpet } ,
{ A3 , Eighth , Trumpet } ,
{ B3 , Eighth , Trumpet } ,
{ D4 , Eighth , Trumpet } ,
{ G4 , Eighth , Trumpet } ,
{ A4 , Eighth , Trumpet } ,
{ B4 , Eighth , Trumpet } ,
{ D5 , Eighth , Trumpet } ,
{ G5 , Eighth , Trumpet } ,
{ A5 , Eighth , Trumpet } ,
{ B5 , Eighth , Trumpet } ,
{ D6 , Eighth , Trumpet } ,
{ E6 , Eighth , Trumpet } ,
{ A6 , Eighth , Trumpet } ,
{ E6 , Eighth , Trumpet } ,
{ D6 , Eighth , Trumpet } ,
{ C6 , Eighth , Trumpet } ,
{ B5 , Eighth , Trumpet } ,
{ F5 , Eighth , Trumpet } ,
{ D5 , Eighth , Trumpet } ,
{ C5 , Eighth , Trumpet } ,
{ B4 , Eighth , Trumpet } ,
{ F4 , Eighth , Trumpet } ,
{ D4 , Eighth , Trumpet } ,
{ C4 , Eighth , Trumpet } ,
{ B3 , Eighth , Trumpet } ,
{ F3 , Eighth , Trumpet } ,
{ D3 , Eighth , Trumpet } ,

{0, Whole, Flute}
};

uint32_t noteIndex = 0;
uint16_t duration_Counter = 0;





//*************ProcessNote********************************************
//  Incremenet through music based on initialized reload value in Timer1 and set pitch
//  Inputs: None
//  Output: none
void ProcessNote(void) {
	
	if(noteIndex > global_Song.note_Num) {
		NVIC_ST_RELOAD_R = 0;
	}
	else if(duration_Counter >= (global_Song.notes[noteIndex].duration*2)) {
		noteIndex++;
		duration_Counter = 0;
		if(global_Song.notes[noteIndex].pitch == 0) {
			NVIC_ST_RELOAD_R = 0;
		}
		else {
			NVIC_ST_RELOAD_R = 80000000 / (global_Song.notes[noteIndex].pitch*64);
			//NVIC_ST_RELOAD_R = 80000000 / (A4*64);
		}
	}
	else {
		duration_Counter++;
		
	}

}
